### ISSUE TITLE
Implement holidays endpoint

### ISSUE THREAD

**Issue by LuisSarmientoM** [Mteheran/api-colombia#103]
Holidays of a year, next holiday etc.

Her and implementation with [JavaScript](https://github.com/juandbc/festivos-colombia/tree/master?tab=readme-ov-file)

**Comment by Mteheran** [comment]
Thank you for supporting api-colombia.com and helping us enhance this project. The ticket was successfully implemented in the most recent deployment.  We will be able now to get the holidays per year and year/month.
