### ISSUE TITLE
Department with id=9 returns 404

### ISSUE THREAD

**Issue by rortizv** [Mteheran/api-colombia#114]
Hello guys.

I've been using your API-Colombia to build a mobile application to show the data from your services/endpoints.  It will also be an open source application like yours.

I've found this: when getting the department with id=9, it doesn't exists, it returns 404, see Swagger's screenshot:

![image](https://github.com/Mteheran/api-colombia/assets/56207509/f3fa94d6-844a-4995-bcfd-353167646034)

**Comment by Mteheran** [comment]
Thanks for reporting this bug! Fixed!
