### ISSUE TITLE
Error al conectar con postman y paquete de python requests

### ISSUE THREAD

**Issue by desarrollaldor2** [Mteheran/api-colombia#116]
Cuando hago un GET a https://api-colombia.com/api/v1/Department en python utilizando el paquete requests obtengo el siguiente error: 
('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))
y cuando utlizo postman obtengo el siguiente error:
Error: read ECONNRESET

**Comment by Mteheran** [comment]
He revisado los endpoints y todo esta correcto por nuestro lado, me puedes confirmas si el error todavia continua? no parece ser de api-colombia

**Comment by Mteheran** [comment]
Siguiendo con este issue, quiero saber @desarrollaldor2  si encontraste la causa y si es posible cerrarlo? depronto api-colombia estuvo caida por un momento o algo así por que parece funcionar correctamente ahora.

**Comment by Mteheran** [comment]
Since we don't have response and the api is working fine I will close this issue.
