### ISSUE TITLE
Image is not available anymore from Wiki  media

### ISSUE THREAD

**Issue by DRojasLey** [Mteheran/api-colombia#117]
### Issue:
Image is not available anymore from Wiki  media

### Affected Presidents:
 Euclídes de Angulo (Diego Euclides de Angulo Lemos)
Guillermo León Valencia Muñoz

### Proposed solution:

Is it possible to use an alternative images?:

##### Official image from the BanRep library:

https://enciclopedia.banrepcultural.org/images/d/d7/Diego_Euclides_de_Angulo.jpg?20171101211726

##### Non official options
https://www.diccionariodecolombia.expert/wp-content/uploads/2020/03/image-545-244x300.png
or
https://www.colombia-sa.com/presidentes/images/diego_euclides_angulo.jpg

#### Guillermo León Valencia Muñoz
Image URL slug changed:
https://es.wikipedia.org/wiki/Guillermo_Le%C3%B3n_Valencia#/media/Archivo:Guillermo_Leon_Valencia_Munoz.jpg
Alternative image:
http://historico.presidencia.gov.co/asiescolombia/presidentes/glvalencia.jpg

Thank you for taking a look

**Comment by Mteheran** [comment]
I will fix both images soon, and thanks for reporting this. In the future, we will save all these images in our storage to avoid dependencies on external links.

**Comment by Mteheran** [comment]
Boths images are fixed, thanks for contributing to this project. 

In the future, we expect our own images in a blob storage.
