### ISSUE TITLE
Feature Proposal: API Documentation

### ISSUE THREAD

**Issue by RijulTP** [Mteheran/api-colombia#118]
Hi there! I'd love to help set up API documentation for your project.  
I've been working with a documentation platform called LiveAPI, and I can get everything set up for you at no cost.

All we ask in return is some feedback or a brief testimonial.  
Feel free to check it out here: [LiveAPI](https://hexmos.com/liveapi).

Also, here is a brief demo of LiveAPI in action.

You can try out the API with the “Try It” button and get the response right away.

![image](https://github.com/user-attachments/assets/2be96520-401e-4f49-8f33-433449036ada)

Plus, if you want to use the API in a specific language, our built-in code generator makes that super easy.

![image](https://github.com/user-attachments/assets/551a8cd4-3869-4621-bee9-09bdc34a4dc8)

**Comment by Mteheran** [comment]
We are only using OpenSource tools for Api-Colombia.com at this moment.
