### ISSUE TITLE
Propuesta de integración con Datos Abiertos Colombia

### ISSUE THREAD

**Issue by Macorreag** [Mteheran/api-colombia#29]
Colombia es uno de los pocos países en Latinoamérica que tiene una plataforma dedicada a la implementación de datos abiertos, puedes mejorar tu API realizando actualizaciones periódicas con una base de datos de carácter Nacional como esta:

https://www.datos.gov.co/Mapas-Nacionales/Departamentos-y-municipios-de-Colombia/xdk5-pm3f

Es solo una mejora que podrías implementar. Feliz tarde y buen proyecto

**Comment by Mteheran** [comment]
Del portal de datos.gov.co se caso la mayoria de datos que tenemos, las descripciones fueron sacada de wikipedia. una integración seria genial por que mantendría los datos actualizados todo el tiempo. Los datos que tenemos no cambian en el tiempo realmente excepto la población. Voy a considerarlo para mas adelante y hacerlo directo en la nube como una función o un servicio como Logic Apps

**Comment by Mteheran** [comment]
Acabe de crear un ticket en nuestro board para tenerlo como tarea futura, procedo a cerrar de momento hasta que lo tengamos listo. Gracias por el feedback.
