### ISSUE TITLE
Add open api swagger definition with examples and schemas

### ISSUE THREAD

**Issue by codesandtags** [Mteheran/api-colombia#32]
Type:  Documentation
Title: Add open API swagger definition
Description: 

I would the initiative, and in order to help more devs to use the API, it would be nice if we can complement the existing open API definition with the schemas and examples.

Current state:

https://api-colombia.com/swagger/index.html

Expected behavior:

https://editor.swagger.io/

As you can see in the above URL you have the schemas examples.

**Comment by Mteheran** [comment]
We already added this information. Thanks for supporting the project.
