### ISSUE TITLE
Add CHANGELOG.md and CONTRIBUTING.md files

### ISSUE THREAD

**Issue by codesandtags** [Mteheran/api-colombia#33]
Type: Documentation
Title: Add CHANGELOG.md and CONTRIBUTING.md 
Description:

Many open-source projects used to have these key files to understand what is happening every release and the rules or steps to contribute. Please could you consider adding these files to help more developers review the changes.

Also please could you consider to setup the labels for this project in order to created better issues and types.

Example: 
https://github.com/tailwindlabs/tailwindcss/blob/master/.github/CONTRIBUTING.md

**Comment by fabianmolinab** [comment]
Could you provide more information on the workflow for a contribution that should be followed by those interested in contributing to the project?
Example which I developed:
https://github.com/codigouranio/clan.sports/blob/development/CONTRIBUTING.md
