### ISSUE TITLE
Typo en region department url

### ISSUE THREAD

**Issue by FelipeVa** [Mteheran/api-colombia#61]
Buenas, espero esten teniendo un excelente dia.

Estaba revisando los endpoints en swagger, y note que el endpoint para obtener los departments de una region tiene un un error en la palabra department.

Si podemos apreciar la ruta `https://api-colombia.com/api/v1/Region/1/deparments`, se ve a primera instancia que la palabra `departments` esta mal escrita, pues esta escrita como `deparments`.

Si tratan de hacer una peticion `GET` al a la siguiente ruta  con la palabra "corregida"`https://api-colombia.com/api/v1/Region/1/departments` dara retornara un 404.

De ante mano, excelente trabajo!

**Comment by Mteheran** [comment]
ya quedo arreglado, muchas gracias @FelipeVa  por reportarlo y ayudarnos con el proyecto
