### ISSUE TITLE
Duda con respecto a los datos

### ISSUE THREAD

**Issue by sjdonado** [Mteheran/api-colombia#65]
Primero que todo, buena idea, kudos!

Estuve navegando sobre los archivos del repo y no he encontrado un `seeder` o algo similar. Asumo que los datos han sido introducidos a mano (tal vez como fuente Wikipedia) uno por uno.

qué planes tienen en mente para mantener la información actualizada con respecto a la fuente?

**Comment by Mteheran** [comment]
Hola sjdonado, hemos utilizado diferentes archivos como de excel con la info que hemos depurado para luego lanzar los queries a la BD directamente. Voy a sacar un backup de la BD en estos dias y compartirlos.

La fuente han sido multiples de wikipedia solo hemos sacados algunas descripciones por ejemplo de los sitios turisticos. Todos los datos han salido de fuentes oficiales del gobierno como datos.gov.co, parques nacionales, aguntin codazi, etc... 

Nosotros siempre estamos actualizados, por que nosotros no manejamos información que cambia en el tiempo como valores de dolar, PIB, población etc.. Mas que todos son fechas historicas, nombres, ubicaciones latitud y longitud etc.. de todas formas en los planes si queremos tener algunos servicios para sincronizar información.

Gracias por el apoyo al proyecto y los kudos.
