### ISSUE TITLE
Typo en city department id

### ISSUE THREAD

**Issue by FelipeVa** [Mteheran/api-colombia#68]
Hey guys!

Encontre de hecho otro typo en este caso en el resource `city`.

Como podemos observar en el siguiente response:

```json
 {
    "id": 1,
    "name": "Leticia",
    "description": "Leticia es un municipio fronterizo colombiano, es la capital del departamento del Amazonas. Se encuentra localizado en el extremo sur del país sobre las márgenes del río Amazonas, al sur del área no municipalizada de Tarapacá y al oriente del municipio de Puerto Nariño. Su extensión territorial es de 5968 km², su altura de 82 metros sobre el nivel del mar",
    "surface": 5968,
    "population": 42280,
    "postalCode": "910001",
    "departamentId": 1,
    "departament": null,
    "touristAttractions": null,
    "presidents": null
  }
```

Se pueden ver dos typos respecto al departamento: `departament` y `departamentId`

Adicionalmente encontre que en el endpoint `Department/{regionId}/naturalareas`, retorna un array de un solo item que es el departament en conjunto con las `naturalAreas`, lo que hace que al consumir la api, debas hacer algo como `response[0]['naturalAreas']`, en vez de `response['naturalAreas']`.

Ademas, al consumir el endpoint `department/{regionId}/cities` se puede ver que retorna directamente el array de `cities`. Por lo que si comparamos este endpoint con el de `naturalAreas`, creo que podemos ver una pequenia incongruencia respecto a la forma en la que se retorna las relaciones, ya que en la primera, retorna el `department` con la relacion de `naturalAreas` y en el endpoint de `cities` retorna directamente la relacion de `cities` sin tener que acceder a esta.

De nuevo, excelente trabajo!

Saludos!

**Comment by Mteheran** [comment]
Gracias por el reporte @FelipeVa estos comentarios y reportes de issues son los que nos ayudan a mejorar día a día y tener una mejor api. Con respecto a los endpoints de cities se hizo para facilitar un poco la forma de leerlo, pero no quiero modificarlos de momento por que puedo afectar a las personas que ya estan usando la API. 

Gracias nuevamente y por favor cualquier otra cosa que encuentres puedes reportarla.
