### ISSUE TITLE
[TYPO] Map endpoint y otros

### ISSUE THREAD

**Issue by FelipeVa** [Mteheran/api-colombia#70]
Hey guys! 

He estado creando un php client de esta api, y mientras trabajaba en ello me encontre un typo en el endpoint de `Map` y `Map/{mapId}`. En el schema de `Map` cuando hace referencia a la relacion del department, esta esta definida como `departamentId` y asi mismo el schema como `departament`.

De hecho lo podemos apreciar en el response:
```json
 {
    "id": 2,
    "name": "Mapa Oficial Político Administrativo de Colombia",
    "description": "Este mapa muestra la división territorial y administrativa del país. En él se pueden visualizar los diferentes estados, provincias, regiones, municipios y sus respectivas capitales.",
    "departamentId": null,
    "urlImages": [
      "https://apicolombiastorage.blob.core.windows.net/maps/2-politicio-administrativo.jpg"
    ],
    "urlSource": "https://geoportal.igac.gov.co/contenido/mapas-nacionales",
    "departament": null
  },
```

Adicionalmente en el endpoint `Department/{departmentId}` indiferente de el `departmentId` que se ponga al parecer siempre retornara un `404`. Mismo caso con los endpoint endpoint `TouristicAttraction/pagedList?Page=1&PageSize=10` y `TouristicAttraction/search/{touristicAttractionName}` estos retornan `404` sin importar los valores que uses.

---

Por último, quiero compartirles de manera publica el repositorio del php client: [api-colombia-php-sdk](https://github.com/FelipeVa/api-colombia-php-sdk) (Aun me encuentro redactando el readme).

Excelente iniciativa!

**Comment by Mteheran** [comment]
Hola Felipe, muchas gracias por reportar todo esto, por personas como tú es que el proyecto puede crecer, mejorar cada día y que tenga sentido para toda la comunidad. Ya todos los errores están corregidos y estarán disponibles en un momento.
Felicitaciones por tu proyecto en PHP me encanta la iniciativa, por favor si puedes publicarlo en algun hosting gratuito seria genial verlo corriendo y darle un vistazo. me gustaria tambien mencionarlo en twitter o linkedin puedes compartirlo y etiquetarme que yo le puedo hacer repost para que llegue a mas personas.
