### ISSUE TITLE
Búsqueda de atracciones turísticas retorna 404

### ISSUE THREAD

**Issue by FelipeVa** [Mteheran/api-colombia#72]
¡Buenas! Feliz viernes.

He notado que usualmente el endpoint `TouristicAttraction/search/{keyword}` siempre retorna `404`. Con realizar una simple búsqueda de `Hacienda napoles` retornará `404`, he intentado con diversos `keywords` y el resultado es el mismo.

Saludos!

**Comment by Mteheran** [comment]
Felipe nuevamente gracias por todos tus aportes y ayudarnos a detectar estos errores. Ya quedaron solucionados. 
https://github.com/Mteheran/api-colombia/pull/73
