### ISSUE TITLE
Report - Incorrect Photo Link for Second President

### ISSUE THREAD

**Issue by Jefersonsteven** [Mteheran/api-colombia#76]
Hey there,

I came across an issue with the photo link for the second president. It appears that the current photo being displayed is incorrect.

Current photo link: ["Current Photo"](https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Jos%C3%A9_Mar%C3%ADa_Campo_Serrano_1.jpg/320px-Jos%C3%A9_Mar%C3%ADa_Campo_Serrano_1.jpg)

Correct photo link: ✅ ["Correct Photo"](https://upload.wikimedia.org/wikipedia/commons/c/cd/Eliseo_Pay%C3%A1n_1.jpg)

I wanted to bring this to your attention so that it can be fixed accordingly.

**Comment by Mteheran** [comment]
Thanks, @Jefersonsteven, for reporting this bug. I just fixed the link.

With your help we will have a better api for all the developers.
