### ISSUE TITLE
Felicitación y nuevas ideas

### ISSUE THREAD

**Issue by earrieta12** [Mteheran/api-colombia#89]
Felicitaciones por esta iniciativa. Muy buen trabajo.

Algunas ideas para implementar: 
- Aeropuertos
- Hidroelectricas
- Alcaldes y Gobernadores 
- Universidades (Instituciones de nivel superior)
- Estadios / Escenarios deportivos

Estoy dispuesto a participar y colaborar si es posible. 
Saludos.

**Comment by Mteheran** [comment]
Hola @earrieta12  muchas gracias por apoyar el proyecto y las felicitaciones. Y claro que nos puedes apoyar. De momento no queremos agregar información que cambie el tiempo como valor de divisas, alcaldes, población etc... Pero las demas que mencionas serian geniales. Por favor te invito a crear un Issue aquí en Gthub con esta info en un Excel y nos compartes la fuente oficial de donde la sacaste entonces nosotros la vaciamos de una a la BD de api-colombia y quedaría disponible para tod@s!
