### ISSUE TITLE
Listado Aeropuertos Colombia

### ISSUE THREAD

**Issue by earrieta12** [Mteheran/api-colombia#92]
Adjunto listado de Aeropuertos de Colombia. Clasificados por tipo(Internacional, Nacional, Militar) y con el código IATA, OACI, Ciudad, Departamento, y número de destinos internacionales.

Fuente: https://es.wikipedia.org/wiki/Anexo:Aeropuertos_de_Colombia

[Listado Aeropuertos Colombia.xlsx](https://github.com/Mteheran/api-colombia/files/13196671/Listado.Aeropuertos.Colombia.xlsx)

**Comment by Mteheran** [comment]
Hola @earrieta1, espectacular, gracias por esta info, necesitamos 2 cositas para poder agregar la info

la primera es que necesito reconfirmar estos datos de una fuente oficial del gobierno, no podemos agregarla de wikipedia. 

Número 2 es necesario agregar las columnas DeparmentId y CityId que serian los Ids del departamento y de la ciudad para poder enlazarlos con la info de Api colombia y de esta manera podemos subirlo enlazando con la info que tenemos

**Comment by Mteheran** [comment]
@earrieta12 La información esta completa y esta genial! a futuro seria genial tener latitud y longitud de la ubicación pero de momento esta info es super valiosa. Voy a dejar este Issue abierto y un par de días subiré la información y estarás dentro de los colaboradores del proyecto. Cualquier otra data que puedas preparar para Api-colombia estaremos agradecidos! 

Gracias por apoyar api-colombia.com

**Comment by earrieta12** [comment]
Hola @Mteheran 

Estuve trabajando de nuevo en el listado, y agregué las coordenadas de los Aeropuertos. 
La información la tomé del repositorio [Datos.gov.co](https://www.datos.gov.co/dataset/Aeropuerto-P/auad-bmvw), pero para ser claros, tuve que corroborar todos los aeropuertos uno a uno con Google Maps para que coincidieran las coordenadas(Algunas coordenadas estaban apuntando a la ciudad y no al aeropuerto) 

Saludos.

[Listado Aeropuertos Colombia.xlsx](https://github.com/Mteheran/api-colombia/files/13260424/Listado.Aeropuertos.Colombia.xlsx)

**Comment by earrieta12** [comment]
Mil disculpas, cerré el Issue. Lo dejo abierto de nuevo, para ser cerrado cuando lo consideres.

**Comment by Mteheran** [comment]
ahora api-colombia.com cuenta con toda la info de los aeropuertos de colombia, gracias Edwin Arrieta @earrieta12 por ayudarnos a pulir y procesar esta información.
